### ISSUE TITLE
Help with setting up the scripts

### ISSUE THREAD

**Issue by getzze** [limaanto/crabfit_ynh#1]
Hey, I wanted to install Crab.fit on a server and I found this repo. I would like to help to maintain it, it seems that only the `install` script was modified so far, is it working well?

**Comment by limaanto** [comment]
Hi there! Sorry for the response delay, I had to get my hands on a testing server to check the state of things.
Currently the install, remove and change_url scripts are working but the backup/restore and upgrade scripts have not been tested.
If you have experience with that kind of scripts, I'll gladly discuss them with you :)
Cheers!

**Comment by limaanto** [comment]
The project matured and is now on the [official repo](https://github.com/YunoHost-Apps/crabfit_ynh). I believe most features are working so I'm closing this issue. Feel free to open a new one in the new repo if something is missing :smiley:
